### ISSUE TITLE
[Question] Why did you use a static archive instead of the salt bootstrap?

### ISSUE THREAD

**Issue by Leopere** [faisyl/alpine-salt#1]
Even just grabbing the latest version possible and watch the salt git for latest pushes.

**Comment by faisyl** [comment]
The salt-bootstrap doesn't work for alpine. The reason I use static versions is to I can control the release to stable versions. I plan to use this on my production boxes at some point and stability was essential.

**Comment by faisyl** [comment]
But feel free to fork and modify as you please. I'll be glad to pull in changes if it meets my requirements as well.

**Comment by Leopere** [comment]
Turns out I can't find a later version.  I still may try this image though.  And thanks for exposing how deep the rabbit hole goes with RancherOS now I need to research that...
